// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: aggr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Total struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
}

func (x *Total) Reset() {
	*x = Total{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Total) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Total) ProtoMessage() {}

func (x *Total) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Total.ProtoReflect.Descriptor instead.
func (*Total) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{0}
}

func (x *Total) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Total) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type Hits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *Total `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Hits) Reset() {
	*x = Hits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hits) ProtoMessage() {}

func (x *Hits) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hits.ProtoReflect.Descriptor instead.
func (*Hits) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{1}
}

func (x *Hits) GetTotal() *Total {
	if x != nil {
		return x.Total
	}
	return nil
}

type Buckets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DocCount uint32 `protobuf:"varint,2,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
}

func (x *Buckets) Reset() {
	*x = Buckets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Buckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buckets) ProtoMessage() {}

func (x *Buckets) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buckets.ProtoReflect.Descriptor instead.
func (*Buckets) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{2}
}

func (x *Buckets) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Buckets) GetDocCount() uint32 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

type SignalCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocCountErrorUpperBound uint32     `protobuf:"varint,1,opt,name=doc_count_error_upper_bound,json=docCountErrorUpperBound,proto3" json:"doc_count_error_upper_bound,omitempty"`
	SumOtherDocCount        uint32     `protobuf:"varint,2,opt,name=sum_other_doc_count,json=sumOtherDocCount,proto3" json:"sum_other_doc_count,omitempty"`
	Buckets                 []*Buckets `protobuf:"bytes,3,rep,name=buckets,proto3" json:"buckets,omitempty"`
}

func (x *SignalCount) Reset() {
	*x = SignalCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalCount) ProtoMessage() {}

func (x *SignalCount) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalCount.ProtoReflect.Descriptor instead.
func (*SignalCount) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{3}
}

func (x *SignalCount) GetDocCountErrorUpperBound() uint32 {
	if x != nil {
		return x.DocCountErrorUpperBound
	}
	return 0
}

func (x *SignalCount) GetSumOtherDocCount() uint32 {
	if x != nil {
		return x.SumOtherDocCount
	}
	return 0
}

func (x *SignalCount) GetBuckets() []*Buckets {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type HistoBuckets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyAsString string       `protobuf:"bytes,1,opt,name=key_as_string,json=keyAsString,proto3" json:"key_as_string,omitempty"`
	Key         uint64       `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	DocCount    uint32       `protobuf:"varint,3,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
	SignalCount *SignalCount `protobuf:"bytes,4,opt,name=signal_count,json=signalCount,proto3" json:"signal_count,omitempty"`
}

func (x *HistoBuckets) Reset() {
	*x = HistoBuckets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoBuckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoBuckets) ProtoMessage() {}

func (x *HistoBuckets) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoBuckets.ProtoReflect.Descriptor instead.
func (*HistoBuckets) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{4}
}

func (x *HistoBuckets) GetKeyAsString() string {
	if x != nil {
		return x.KeyAsString
	}
	return ""
}

func (x *HistoBuckets) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *HistoBuckets) GetDocCount() uint32 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

func (x *HistoBuckets) GetSignalCount() *SignalCount {
	if x != nil {
		return x.SignalCount
	}
	return nil
}

type Histogram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buckets  []*HistoBuckets `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Interval string          `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *Histogram) Reset() {
	*x = Histogram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Histogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Histogram) ProtoMessage() {}

func (x *Histogram) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Histogram.ProtoReflect.Descriptor instead.
func (*Histogram) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{5}
}

func (x *Histogram) GetBuckets() []*HistoBuckets {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *Histogram) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type Aggregations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Histogram *Histogram `protobuf:"bytes,1,opt,name=histogram,proto3" json:"histogram,omitempty"`
}

func (x *Aggregations) Reset() {
	*x = Aggregations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aggregations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregations) ProtoMessage() {}

func (x *Aggregations) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregations.ProtoReflect.Descriptor instead.
func (*Aggregations) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{6}
}

func (x *Aggregations) GetHistogram() *Histogram {
	if x != nil {
		return x.Histogram
	}
	return nil
}

type Aggrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Took         uint32        `protobuf:"varint,1,opt,name=took,proto3" json:"took,omitempty"`
	TimedOut     bool          `protobuf:"varint,2,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Hits         *Hits         `protobuf:"bytes,4,opt,name=hits,proto3" json:"hits,omitempty"`
	Aggregations *Aggregations `protobuf:"bytes,5,opt,name=aggregations,proto3" json:"aggregations,omitempty"`
}

func (x *Aggrs) Reset() {
	*x = Aggrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aggrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggrs) ProtoMessage() {}

func (x *Aggrs) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggrs.ProtoReflect.Descriptor instead.
func (*Aggrs) Descriptor() ([]byte, []int) {
	return file_aggr_proto_rawDescGZIP(), []int{7}
}

func (x *Aggrs) GetTook() uint32 {
	if x != nil {
		return x.Took
	}
	return 0
}

func (x *Aggrs) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *Aggrs) GetHits() *Hits {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *Aggrs) GetAggregations() *Aggregations {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

var File_aggr_proto protoreflect.FileDescriptor

var file_aggr_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x67, 0x67, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a,
	0x0a, 0x04, 0x48, 0x69, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x38, 0x0a, 0x07, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x1b, 0x64, 0x6f, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x75, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x17, 0x64, 0x6f, 0x63, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x55, 0x70, 0x70, 0x65, 0x72, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x73, 0x75, 0x6d, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x64, 0x6f, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x10, 0x73, 0x75, 0x6d, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x28, 0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x52, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x0c,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d,
	0x6b, 0x65, 0x79, 0x5f, 0x61, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x65, 0x79, 0x41, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x35, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x09, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x12, 0x2d, 0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x3e,
	0x0a, 0x0c, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e,
	0x0a, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x52, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x92,
	0x01, 0x0a, 0x05, 0x41, 0x67, 0x67, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x68, 0x69, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x48, 0x69, 0x74, 0x73, 0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x0c, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aggr_proto_rawDescOnce sync.Once
	file_aggr_proto_rawDescData = file_aggr_proto_rawDesc
)

func file_aggr_proto_rawDescGZIP() []byte {
	file_aggr_proto_rawDescOnce.Do(func() {
		file_aggr_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggr_proto_rawDescData)
	})
	return file_aggr_proto_rawDescData
}

var file_aggr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_aggr_proto_goTypes = []interface{}{
	(*Total)(nil),        // 0: proto.Total
	(*Hits)(nil),         // 1: proto.Hits
	(*Buckets)(nil),      // 2: proto.Buckets
	(*SignalCount)(nil),  // 3: proto.SignalCount
	(*HistoBuckets)(nil), // 4: proto.HistoBuckets
	(*Histogram)(nil),    // 5: proto.Histogram
	(*Aggregations)(nil), // 6: proto.Aggregations
	(*Aggrs)(nil),        // 7: proto.Aggrs
}
var file_aggr_proto_depIdxs = []int32{
	0, // 0: proto.Hits.total:type_name -> proto.Total
	2, // 1: proto.SignalCount.buckets:type_name -> proto.Buckets
	3, // 2: proto.HistoBuckets.signal_count:type_name -> proto.SignalCount
	4, // 3: proto.Histogram.buckets:type_name -> proto.HistoBuckets
	5, // 4: proto.Aggregations.histogram:type_name -> proto.Histogram
	1, // 5: proto.Aggrs.hits:type_name -> proto.Hits
	6, // 6: proto.Aggrs.aggregations:type_name -> proto.Aggregations
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_aggr_proto_init() }
func file_aggr_proto_init() {
	if File_aggr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aggr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Total); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Buckets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoBuckets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Histogram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aggregations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aggrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aggr_proto_goTypes,
		DependencyIndexes: file_aggr_proto_depIdxs,
		MessageInfos:      file_aggr_proto_msgTypes,
	}.Build()
	File_aggr_proto = out.File
	file_aggr_proto_rawDesc = nil
	file_aggr_proto_goTypes = nil
	file_aggr_proto_depIdxs = nil
}
